/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SlidingObjectTest")]
    [LuaRegisterType(0x151435454c775416, typeof(LuaBehaviour))]
    public class SlidingObjectTest : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "7e63c4f16c4f5ad47968d4a8335096d3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Vector3 m_leftEndpoint = new Vector3(0f, 0f, 0f);
        [SerializeField] public UnityEngine.Vector3 m_rightEndpoint = new Vector3(0f, 0f, 0f);
        [SerializeField] public UnityEngine.Vector3 m_originalPosition = new Vector3(0f, 0f, 0f);
        [SerializeField] public UnityEngine.GameObject m_button = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_leftEndpoint),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_rightEndpoint),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_originalPosition),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_button),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/SlidingObjectTest/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
